### ISSUE TITLE
Нужен заголовок для группы вапиантов использования, название "сценарии" 

### ISSUE THREAD

**Issue by Vadimber2** [Vadimber2/xpertnetz_framer#16]
![telegram-cloud-photo-size-2-5381842000871022087-y](https://github.com/Vadimber2/xpertnetz_framer/assets/19520821/c5e79d31-7670-4b52-ac60-15d0a7379411)

**Comment by akklimoff** [comment]
добавлено
![image](https://github.com/Vadimber2/xpertnetz_framer/assets/145140777/7a4dbd67-9ba7-4123-b1c7-7b098442a1d2)
